# Generated by Django 4.2.10 on 2024-02-28 19:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransformerSpecification',
            fields=[
                ('transformer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('power_rating', models.PositiveBigIntegerField(default=100)),
                ('transformer_type', models.CharField(choices=[('SINGLE', 'SINGLE PHASE TRANSFORMER'), ('THREE', 'THREE PHASE TRANSFORMER')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='TransformerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('out_ua', models.FloatField(default=0)),
                ('out_ub', models.FloatField(default=0)),
                ('out_uc', models.FloatField(default=0)),
                ('out_ia', models.FloatField(default=0)),
                ('out_ib', models.FloatField(default=0)),
                ('out_ic', models.FloatField(default=0)),
                ('out_uab', models.FloatField(default=0)),
                ('out_ubc', models.FloatField(default=0)),
                ('out_uca', models.FloatField(default=0)),
                ('out_pa', models.FloatField(default=0)),
                ('out_pb', models.FloatField(default=0)),
                ('out_pc', models.FloatField(default=0)),
                ('out_qa', models.FloatField(default=0)),
                ('out_qb', models.FloatField(default=0)),
                ('out_qc', models.FloatField(default=0)),
                ('out_sa', models.FloatField(default=0)),
                ('out_sb', models.FloatField(default=0)),
                ('out_sc', models.FloatField(default=0)),
                ('out_freq', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('ON', 'Transformer Online'), ('OFF', 'Transformer Offline'), ('OVERLOADED', 'Transformer Overloaded')], default='ON', max_length=15)),
                ('transformer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transformerspecification')),
            ],
        ),
    ]
