# Generated by Django 4.2.10 on 2024-03-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformerspecification',
            name='transformer_id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
